name: Release eslint-config-www

on:
  push:
    branches:
      - main
    paths:
      - TypeScript/eslint-www/**
  workflow_dispatch:

permissions:
  id-token: write # for OIDC
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release eslint-config-www
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TypeScript/eslint-www

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install Dependencies
        run: npm install

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1.5.1
        with:
          version: npm run changeset version
          publish: npm run release
          title: 'chore(eslint-www): release x.y.z'
          cwd: ./TypeScript/eslint-www
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          createGithubReleases: false
