name: Release eslint-config-www

on:
  push:
    branches:
      - master
    paths:
      - TypeScript/eslint-www/**
  workflow_dispatch:

jobs:
  release:
    name: Release eslint-config-www
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TypeScript/eslint-www

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: npm run changeset version
          publish: npm run release
          cwd: ./TypeScript/eslint-www
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          createGithubReleases: false
